<a href="https://colab.research.google.com/github/rda12345/Machine-Learning/blob/main/MIT6_036_hw06_colab_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MIT 6.036 Spring 2019: Homework 6

This homework does not include provided Python code. Instead, we encourage you to write your own code to help you answer some of these problems, and/or test and debug the code components we do ask for. All of the problems should be simple enough that hand calculation should be possible, but it may be convenient to write some short programs to explore the neural networks, particularly for problem 2.


In [2]:
import numpy as np

def SM(z):
  # implement softmax
  return np.exp(z)/np.sum(np.exp(z))

 **Problem 2A**

In [3]:
z = np.array([[-1, 0, 1]]).T
a = SM(z)
print(a)

[[0.09003057]
 [0.24472847]
 [0.66524096]]


**Problem 2.C-F**

In [6]:
w = np.array([[1, -1, -2], [-1, 2, 1]])
x = np.array([[1], [1]])
y = np.array([[0, 1, 0]]).T

z = np.dot(w.T,x)
a = SM(z)

def NLL_grad_w(x,y,a):
    return x*(a-y).T



print(f'Q2C: {NLL_grad_w(x, y, a)}')


print(f'Q2D: {a[1,0]}')

## Q2E
step_size = 0.5
w_new = w - step_size*NLL_grad_w(x,y,a)
print(f'Q2E: {w_new}')

## Q2F
z_new = np.dot(w_new.T,x)
a_new = np.exp(z_new)/np.sum(np.exp(z_new))
print(f'Q2F: {a_new[1,0]}')


Q2C: [[ 0.24472847 -0.33475904  0.09003057]
 [ 0.24472847 -0.33475904  0.09003057]]
Q2D: 0.6652409557748219
Q2E: [[ 0.87763576 -0.83262048 -2.04501529]
 [-1.12236424  2.16737952  0.95498471]]
Q2F: 0.7724528366207931


**Problem 3**

In [36]:
# layer 1 weights
w_1 = np.array([[1, 0, -1, 0], [0, 1, 0, -1]])
w_1_bias = np.array([[-1, -1, -1, -1]]).T
# layer 2 weights
w_2 = np.array([[1, -1], [1, -1], [1, -1], [1, -1]])
w_2_bias = np.array([[0, 2]]).T

x = np.array([[3,14]]).T
z = np.dot(w_1.T,x)+w_1_bias
a_1 = np.where(z > 0, z, 0)
print(f'Q3.1: {a_1.T[0]}')

z_2 = np.dot(w_2.T,a_1)+ w_2_bias

a_2 = SM(z_2)

print(f'Q3.2: {a_2.T.tolist()[0]}')

x = np.array([[0.5,0.5],[0,2],[-3,0.5]]).T
z = np.dot(w_1.T,x)+w_1_bias
a_1 = np.where(z > 0, z, 0)
print(f'Q3.2C: {a_1.tolist()}')

a_1_new = np.array([[0,0,0,0]]).T
z_2_new = np.dot(w_2.T,a_1_new)+ w_2_bias
a_2_new = SM(z_2_new)

print(f'Q3.3A: {a_2_new.T.tolist()[0][0]}')

print(f'Q3.3B: {a_2_new.T.tolist()[0][1]}')

z2_1 = 1
z2_2 = 1
z2 = np.array([[z2_1,z2_2]]).T

print(f'Q3.D,E {SM(z2).T.tolist()[0]}')

z2_1 = 3
z2_2 = -1
z2 = np.array([[z2_1,z2_2]]).T

print(f'Q3.F,G {SM(z2).T.tolist()[0]}')


Q3.1: [ 2 13  0  0]
Q3.2: [0.9999999999993086, 6.914400106935422e-13]
Q3.2C: [[0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 2.0], [0.0, 0.0, 0.0]]
Q3.3A: 0.11920292202211755
Q3.3B: 0.8807970779778824
Q3.D,E [0.5, 0.5]
Q3.F,G [0.9820137900379085, 0.01798620996209156]


In [ ]:
import numpy as np

T  = np.matrix([[0.0 , 0.1 , 0.9 , 0.0],
[0.9 , 0.1 , 0.0 , 0.0],
[0.0 , 0.0 , 0.1 , 0.9],
[0.9 , 0.0 , 0.0 , 0.1]])
g = 0.9
r = np.matrix([0, 1., 0., 2.]).reshape(4, 1)

print(np.linalg.solve(np.eye(4) - g * T, r))

[[6.05288295]
 [6.48663207]
 [6.7519581 ]
 [7.58553317]]
